manipulator:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # posiiton controller
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: q1
    pid: {p: 1000.0, i: 0.0, d: 1.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: q2
    pid: {p: 1000.0, i: 0.0, d: 1.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: q3
    pid: {p: 1000.0, i: 0.0, d: 1.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: q4
    pid: {p: 1000.0, i: 0.0, d: 1.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: q5
    pid: {p: 1000.0, i: 0.0, d: 1.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: q6
    pid: {p: 100.0, i: 0.01, d: 10.0}